# Generated by Django 5.2.1 on 2025-06-03 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_invoice_payment_receipt_tenantprofile_payment_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedsitter',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bedsitter',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bedsitters', to='portal.apartment'),
        ),
    ]
