# Generated by Django 5.2.1 on 2025-06-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_bedsitter_is_available_alter_bedsitter_apartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bedsitter',
            name='is_available',
        ),
    ]
