# Generated by Django 5.2.1 on 2025-06-20 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_bedsitter_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.tenantprofile'),
        ),
    ]
