# Generated by Django 5.2.3 on 2025-06-26 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_apartment_options_alter_bedsitter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='apartment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.apartment'),
        ),
    ]
